//
// Created by ojg on 1/26/20.
//

#ifndef QMK_FIRMWARE_CONFIG_H
#define QMK_FIRMWARE_CONFIG_H

#define RGB_MATRIX_STARTUP_HUE 40
#define RGB_MATRIX_STARTUP_SAT 255-3*17

#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_COLOR

#endif //QMK_FIRMWARE_CONFIG_H
